import{a as b,S as p,i as L}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();async function h(n,r,s){try{return(await b.get(`https://pixabay.com/api/?key=42026920-e619b387ca2127f1aff40b8e2&q=${n}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${s}`)).data}catch(o){throw console.error("Error fetching data:",o),o}}function y(n){return n.hits.map(r=>`<li class="gallery-item"><a href="${r.webformatURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}"></a>
          <div class='comments'>
          <p><b>Likes: </b>${r.likes}</p>
          <p><b>Views: </b>${r.views}</p>
          <p><b>Comments: </b>${r.comments}</p>
          <p><b>Downloads: </b>${r.downloads}</p>
          </div>
          </li>`).join("")}const w=document.querySelector("#form"),d=document.querySelector(".loader"),u=document.querySelector(".gallery"),m=document.querySelector(".load-btn");let a,f=15,c="",l;const g={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",animation:250,widthRatio:.9,scaleImageToRatio:!0};document.addEventListener("DOMContentLoaded",()=>{w.addEventListener("submit",async e=>{if(e.preventDefault(),c=document.getElementById("search").value.trim(),!c||c===" ")return o("The search field should not be empty");a=1,d.classList.remove("hidden"),m.classList.remove("hidden"),u.innerHTML="";try{const t=await h(c,a,f),i=y(t);u.insertAdjacentHTML("beforeend",i),l=new p(".gallery a",g),l.refresh()}catch(t){console.error("Error fetching data:",t)}finally{d.classList.add("hidden")}}),m.addEventListener("click",n);async function n(){a+=1,d.classList.remove("hidden");try{const e=await h(c,a,f),t=y(e);l.destroy(),u.insertAdjacentHTML("beforeend",t),l=new p(".gallery a",g),l.refresh(),s(),a*f>=e.totalHits&&r()}catch(e){console.error("Error fetching data:",e)}finally{d.classList.add("hidden")}}function r(){m.classList.add("hidden"),o("We're sorry, but you've reached the end of search results.")}function s(){const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}function o(e){L.error({title:"",backgroundColor:"#EF4040",message:e,position:"topRight"})}});
//# sourceMappingURL=commonHelpers.js.map
