import{a as u,i as m,S as y}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&s(o)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();const f=document.querySelector("#form"),a=document.querySelector(".loader"),h=document.querySelector(".gallery"),i=document.querySelector(".load-btn");let n,g=15,c="",d;const b={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",animation:250,widthRatio:.9,scaleImageToRatio:!0};document.addEventListener("DOMContentLoaded",()=>{f.addEventListener("submit",async e=>{if(e.preventDefault(),c=document.getElementById("search").value.trim(),!!c){n=1,a.classList.remove("hidden"),i.classList.remove("hidden"),h.innerHTML="";try{const o=(await u.get(`https://pixabay.com/api/?key=42026920-e619b387ca2127f1aff40b8e2&q=${c}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=15`)).data;s(o)}catch(t){console.error("Error fetching data:",t)}finally{a.classList.add("hidden")}}}),i.addEventListener("click",p);async function p(){n+=1,a.classList.remove("hidden");try{const t=(await u.get(`https://pixabay.com/api/?key=42026920-e619b387ca2127f1aff40b8e2&q=${c}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=${g}`)).data;d.destroy(),s(t),l(),n*g>=t.totalHits&&(i.classList.add("hidden"),r())}catch(e){console.error("Error fetching data:",e)}finally{a.classList.add("hidden")}}function r(){i.classList.add("hidden"),m.error({title:"",backgroundColor:"#EF4040",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}function l(){const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}function s(e){if(e.hits.length===0)i.classList.add("hidden"),m.error({title:"",backgroundColor:"#EF4040",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{const t=e.hits.map(o=>`<li class="gallery-item"><a href="${o.webformatURL}">
          <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}"></a>
          <div class='comments'>
          <p><b>Likes: </b>${o.likes}</p>
          <p><b>Views: </b>${o.views}</p>
          <p><b>Comments: </b>${o.comments}</p>
          <p><b>Downloads: </b>${o.downloads}</p>
          </div>
          </li>`).join("");h.insertAdjacentHTML("beforeend",t),d=new y(".gallery a",b),d.refresh(),f.reset()}}});
//# sourceMappingURL=commonHelpers.js.map
